import numpy as np
import pandas as pd

### Multiline statements and strings

In [15]:
a = [1,
    2, #two
    4]

In [16]:
b = [3,
    3,
    3]


In [37]:
def my_func(a, #comment
           b, # comments
           c #now here parenthesis shoud be inline with above parenthesis
           ):
    print(a,b,c)

In [38]:
my_func(10, #comments if  required
       20,
       70 #comments if req
       )

10 20 70


### How to add List

In [39]:
c = np.array([a+b])
c

array([[1, 2, 4, 3, 3, 3]])

In [43]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7,8,9]

zipped_lists = zip(list1, list2,list3)

sum = [x + y + z for (x, y, z) in zipped_lists]


print(sum)

[12, 15, 18]


### of \n or \t to break the string

In [44]:
print('let wait fot it'\
     ' to see codes')

let wait fot it to see codes


In [45]:
print('let wait fot it\nto see codes')

let wait fot it
to see codes


### Line continuation Character

In [61]:
a = 4
b = 20
c = 25

if a > 2 \
and b > 10 \
and c > 12:
    print('Yes') #comments

Yes


### Multi line string

In [62]:
a = '''this is a 
string'''
a

'this is a \nstring'

In [63]:
print(a)

this is a 
string


In [65]:
b = '''How you
       doing and it captues all the spaces 
    and characters'''
print(b)

How you
       doing and it captues all the spaces 
    and characters


In [69]:
c="""this also captures any 
          of the spaces of 
          character mentioned"""
c

'this also captures any \n          of the spaces of \n          character mentioned'

In [70]:
print(c)

this also captures any 
          of the spaces of 
          character mentioned


### Define function and Usuage of Lambda function

In [73]:
def my_func(a,b):
    return a * b

In [74]:
my_func([1,3], 3)

[1, 3, 1, 3, 1, 3]

In [75]:
# how to define function that is not even created as python gives option to create function before calling it
def my_func1():
    return func2()

def func2():
    return 'running func2'

In [76]:
my_func1()

'running func2'

In [78]:
type(func2)

function

In [79]:
# Lamda define function however doesn't give a name
lambda x: x**2

<function __main__.<lambda>(x)>

In [80]:
f1 = lambda x: x**2
f1(2)

4

In [84]:
# how to see assign function to other function
func3 = my_func1
func3()

'running func2'

### While Loop
It repeats the block of codes as long as it's true

In [ ]:
i= 0
while i < 5:
    i+1
print(i)

In [93]:
i = 0
while i < 5:
    print(i)
    i+=1

0
1
2
3
4


In [95]:
min_length = 2

while True:
    name = input('Please enter your name:')
    if len(name) >= min_length and name.isprintable() and name.isalpha():
        break
print('Hello, {0}'.format(name))

Please enter your name:hame
Hello, hame


In [67]:
# to find out text is alpha or alpha-numeric
txt = "Company10"

x = txt.isalpha()

print(x)

False


### For Loop
It iterates on range(), list[], 'string', tuples()

In [106]:
# to iterates on tuple in list and unpack it
for i , j in [(1,2), (2,3), (3,4), (4,5)]:
    print(i,j)

1 2
2 3
3 4
4 5


In [107]:
# to iterate over string
for i in 'string':
    print(i)

s
t
r
i
n
g


In [73]:
# to continue iterating loop
for i in range(5):
    if i==3:
        
    print(i)

0
1
2
4


In [136]:
# to break the loop
for i in range(1,9):
    print(i)
    if i%7==0:
        break
    

1
2
3
4
5
6
7


In [142]:
# use enumerate to get the index
s = 'hello'
for i in enumerate(s):
    print(i)

(0, 'h')
(1, 'e')
(2, 'l')
(3, 'l')
(4, 'o')


# **To make it more bolder**

In [1]:
# ** To make it more bolder**
# *to make it slant*

# *Slant word*

## Factorial & Exponents
### To write factorial we have to methods
1. from math import factorial
2. factorial = 6**6

In [9]:
# let's import library
from math import factorial
factorial(5) # n! = n * (n-1) * (n-2) * ...

120

In [38]:
# second using without library
n = 23
fact = 1
  
for i in range(1,1+n):
    fact = fact * i
      
print ("The factorial of 23 is : ",end="")
print (fact)

The factorial of 23 is : 25852016738884976640000


In [14]:
# Exponents are n^n = n * n * n * ...
5**5 #5*5*5*5*5

3125

#### Strings can be concatenated (glued together) with the + operator, and repeated with *:

In [15]:
3 * 'un' + 'ium' #https://docs.python.org/3/tutorial/introduction.html

'unununium'

In [20]:
q='python'

In [25]:
print(q[:4] +q[4:])

python


In [29]:
a, b = 0,1
while a < 10:
    print(a)
    a, b = b, a+b

0
1
1
2
3
5
8


In [54]:
x=int(input('enter the digit'))

for i in range(1, x):
    x = x*i
    print(x)


enter the digit5
5
10
30
120


In [ ]:
def x(a,b):
    result(a+b)
    print(result);
    
c = int(input())
d = int(input())
y = (c+d)
print(y)

Task
Given an integer, , perform the following conditional actions:

If  is odd, print Weird
If  is even and in the inclusive range of  to , print Not Weird
If  is even and in the inclusive range of  to , print Weird
If  is even and greater than , print Not Weird

In [44]:
n = int(input())

if n % 2 == 1:
    print('Weird')
elif n <=5:
    print('Not Weird')
elif <=20 and n % 2 == 0:
    print('Weird')
# elif n > 20 and n % 2 == 0:
#     print('Not Weird')
else:
    print('Not Weird')
    



20
Not Weird


from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score
X, y = datasets.load_iris(return_X_y=True)

In [45]:
from sklearn import svm, datasets 
from sklearn.model_selection import cross_val_score
X, y = datasets.load_iris(return_X_y=True)

In [49]:
import pandas as pd
import numpy as np
df = pd.DataFrame(X,y)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 5.9 KB


### Hacker Rank - 30 Days Code Challege

#### Day 1

In [4]:
import numpy as np
import pandas as pd
i = 5
d= 12.0
s= "let's do it!"

In [14]:
# day 2
def solve(meal_cost):
    tip_percent = meal_cost*20/100
    tax_percent = meal_cost*8/100
    total_cost = meal_cost + tip_percent + tax_percent
    print(round(total_cost))


In [15]:
solve(12)

15


In [2]:
# Day 3 Compare the triplets

N = int(input())

if N % 2 == 1:
    print('Weird')
elif N <=5:
    print('Not Weird')
elif N <=20 and n % 2 == 0:
    print('Weird')
# elif n > 20 and n % 2 == 0:
#     print('Not Weird')
else:
    print('Not Weird')

35
Weird


In [ ]:
# Day 4 Class Vs Instance


In [16]:
import numpy as np

In [19]:
a = np.array([[2,7,1],[-2,1,8],[3,4,-2]])
b = np.array([[8,1,3], [3,5,8], [7,-2,-4]])
a

array([[ 2,  7,  1],
       [-2,  1,  8],
       [ 3,  4, -2]])

In [18]:
c = a @ b
c

array([[ 44,  35,  58],
       [ 43, -13, -30],
       [ 22,  27,  49]])

In [20]:
### matrix inverse
x = np.array([[2,1,1], [3,2,1], [2,1,2]])
x

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [22]:
y = np.linalg.inv(x)
y

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [25]:
z = np.linalg.inv(y)
z

array([[2., 1., 1.],
       [3., 2., 1.],
       [2., 1., 2.]])

In [52]:
a = np.array([[-4,2], [-6,3]])
a

array([[-4,  2],
       [-6,  3]])

In [47]:
c = np.linalg.inv(b)

In [42]:
c

array([[ 4., -3.],
       [18., -9.]])

In [44]:
1/6

0.16666666666666666

$$ x_i = \left( \begin{array}{c} w_i \\ h_i \\ l_i \end{array} \right) \quad\text{and}\quad x_i^T = \left( w_i, h_i, l_i \right)\,. $$

In [ ]:
$$ x_i = \left( \begin{array}{c} w_i \\ h_i \\ l_i \end{array} \right) \quad\text{and}\quad x_i^T = \left( w_i, h_i, l_i \right)\,. $$

In [13]:
import numpy as np
a = np.array([[7,3],[3,1]])
b= np.array([3,1])

In [14]:
a

array([[7, 3],
       [3, 1]])

In [15]:
c = a @ b
c

array([24, 10])

In [16]:
d = np.linalg.inv(a)
d

array([[-0.5,  1.5],
       [ 1.5, -3.5]])

In [7]:
import pandas as pd
import numpy as np

i = 1
while i < 5:
    j=1
    while j < 5:
        print(j)
        j=j+1
    i=i+1

1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4


In [27]:
# Pymarid printing of 5 rows

i = 1

while i <= 5:
    j = 1
    while j <= i:
        print('*', end='')
        j = j + 1
    print()
    i = i +1


*
**
***
****
*****


In [37]:
# pyramind printing of 1 to 5 digits in each rows with same number of digit counts
i = 1
while i <= 5:
    j = 1
    while j <= i:
        print(i, end='')
        j = j+1
    print()
    i = i+1



1
22
333
4444
55555


In [38]:
# pyramind printing of 1 to 5 digits in sequence in each rows
i = 1
while i <= 5:
    j = 1
    while j <= i:
        print(j, end='')
        j = j+1
    print()
    i = i+1

1
12
123
1234
12345


### Fibonacci Series Practice

In [20]:
def fib(n):
    a = 0
    b = 1
    print(a)
    print(b)
    for i in range(2, n):
        c= a+b
        a= b
        b= c
        print(c)
    


In [21]:
fib(10)

0
1
1
2
3
5
8
13
21
34


In [81]:
# Other way to write fibnacci series
def fib(n):
        if n == 1:
            return 0
        if n == 2:
            return 1
        return(fib(n-1) + fib(n-2))

n = int(input('Enter the digit: '))
for i in range(1,n+1):
    print(fib(i))
    

Enter the digit: 5
0
1
1
2
3


3

### Factorial
    

In [2]:
def fact(n):
    if n == 1:
        return 1
    else:
        return(n*fact(n-1))
n = int(input('Enter the digit: '))
z = fact(n)
print('Factorial: ', z)

Enter the digit: 5
Factorial:  120


In [22]:
# how to print factor of any number
n = 25
for i in range(1,n+1):
    if n%i==0:
        print(i)
    

1
5
25


### Find the nth largest number

In [36]:
l = [4,5,3,7,9,0,12,34,22,5,6,7,0]
n=3
sorted(list(set(l)))


[0, 3, 4, 5, 6, 7, 9, 12, 22, 34]

In [84]:
import pandas as pd
df = pd.DataFrame({
        'student': [
            'monica', 'nathalia', 'anastasia', 'marina', 'ema'
        ],

    'grade' : ['excellent', 'excellent', 'good', 'very good', 'good'
    ]
    })

print (df)
    

     student      grade
0     monica  excellent
1   nathalia  excellent
2  anastasia       good
3     marina  very good
4        ema       good


In [99]:
df.sort_index(axis=0, inplace=False)

student      grade
0     monica  excellent
1   nathalia  excellent
2  anastasia       good
3     marina  very good
4        ema       good

In [100]:
16**2

256

In [4]:
n=4
for i in range(n):
    for j in range(n):
        if i==0 or i== n-1 or j==0 or j==n-1:
            print(0,end="")
        else:
            print(1, end="")
    print()

0000
0110
0110
0000


In [10]:
L=[]
for i in range(n):
    t = []
    for j in range(n):
        if i==0 or i== n-1 or j==0 or j==n-1:
            t.append(0)
        else:
            t.append(1)
    L.append(t)

In [11]:
L

[[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]

In [15]:
# print Z using 1 and 0
n=6
for i in range(n):
    for j in range(n):
        if i==0 or i== n-1 or j==0 or j==n-1:
            print(1,end='')
        else:
            print(0,end='')
    print()

111111
100001
100001
100001
100001
111111


In [18]:
# using list
n = 6
o = []
for i in range(n):
    t = []
    for j in range(n):
        if i==0 or i==n-1 or j==0 or j==n-1:
            t.append(1)
        else:
            t.append(0)
    o.append(t)
    
    

In [19]:
o

[[1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1]]

In [ ]:
#create a pattern
l=[]
for i in range(1,input1+1):
    l.append('_'*(input1-1)+'*'*i)
return 1
pass

In [48]:
for i in range():
    if i= int(input('Enter digit: '))

Enter digit: 18


#### write a program to print each number as count of it's own.

In [13]:
n = int(input('Enter the digit: '))
for i in range(n+1):
    for j in range(i):
        print(i)

Enter the digit: 3
1
2
2
3
3
3


#### write a program to print prime number between 1 to 20.

In [27]:
# n = int(input('Enter the digit: '))
for i in range(1,20):
    flag=True
    for j in range(2,i):
        if i%j==0:
            print(i,'is not a prime number', j)
            flag=False
            break
    if flag==True:
        print(i)
            

1
2
3
4 is not a prime number 2
5
6 is not a prime number 2
7
8 is not a prime number 2
9 is not a prime number 3
10 is not a prime number 2
11
12 is not a prime number 2
13
14 is not a prime number 2
15 is not a prime number 3
16 is not a prime number 2
17
18 is not a prime number 2
19


In [ ]:
as=1
as

In [1]:
L=[2, 3, 4, 2, 1, 2, 3]
print(L.index(2))

0


In [10]:
L = [2, 1, 2, 4, 5, 3, 6]
K = L.index(4)
# K= 4 in L
K

3

In [14]:
B = [45, 35, 25]
A = [10, 20, 30]

In [15]:
B.extend(A)
B

[45, 35, 25, 10, 20, 30]

### Calendar clash (Wedding Date)

In [21]:
list1=[ [29,31], [23,26], [24,25] ]
wed_date=int(input())

clash=0
for i in list1:
    if i[0] <= wed_date and i[1] >= wed_date:
        clash=clash+1
print(clash)

28
0


In [18]:
for i in list1:
    print(i)

[29, 31]
[23, 26]
[24, 25]


In [22]:
print(chr(51))

3


In [28]:
# finding the ASCII value of an integer
def convertToASCII(N):
 
    num = str(N)
#     i = 0
     
    for ch in num:
        print(ch, "(", ord(ch), ")")
 
# Driver Code
N = 36
 
convertToASCII(N)

3 ( 51 )
6 ( 54 )


In [41]:
S=' sting  '
a = S.strip()
b='bee'
c=b+a
c

'beesting'

In [29]:
chr(123)

'{'

### finding the longest common prefix in two strings

In [47]:
s1="programsbuzz"
s2="programming"

l1 = len(s1)
l2 = len(s2)
l3 = min(l1,l2)
l3

for i in range(l3):
    if s1[i]!=s2[i]:
        break
if i == 0:
    print(-1)
else:
    print(s1[:i])

program


In [53]:
a='diversity'
z='universit'
d=len(z)
b=len(a)
c=min(b,d)
c

9

### Comprehension

In [10]:
# list comprehension
L1 = [10, 20, 30, 24, 18]

In [17]:
l3=[]
for i in L1:
    l3.append(i)

In [18]:
l3

[10, 20, 30, 24, 18]

In [27]:
L1 = [10, 20, 30, 24, 18]
L2 = [8, 14, 15, 20, 10]
L3 = []
for  i in range(len(L1)):
    L3.append(L1[i] - L2[i])
L3

[2, 6, 15, 4, 8]

In [12]:
for i in range(len(L1)):
    l3=i+i

In [13]:
l3

8

In [31]:
# dictionary comprehension 
updated_dict = {i : i**2 for i in range(2,21) if i % 2 ==0}
print(updated_dict)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324, 20: 400}


In [34]:
# define function
def factorial(n):
    fact=1
    for i in range(1,n+1):
        fact= fact*i
    return fact

factorial(5)

120

In [38]:
def x_mul_y(x,y):
    outcome=0
    for i in range(x,y):
        outcome=x**y
    return outcome

x_mul_y(6,7)

279936

In [45]:
def func(x, y=1):
    z = x * y + x + y
    return z

func(2, func(3))

23

In [46]:
def func(x = 1 ,y = 2):
    z = x * y + x + y
    return z

func(2, func(3))

35

### Lambda function

In [47]:
# creating lambda function
f = lambda x,y: x if x>y else y
f(2,3)

3

### Map, Filter and Reduce Functions

map(function,iterable object)

    - The function here can be a lambda function or a function object.

    - The iterable object can be a string, list, tuple, set or dictionary.

In [49]:
countries=['India', 'Japan', 'Russia', 'USA']

f = lambda x: x.upper()
f('India')

'INDIA'

In [62]:
# using for loop on entire list to changed it to upper case

def upper_case(a):
    l=[]
    for i in countries:
        l.append(i.upper())
    return l
        
upper_case(countries)
        
    

['INDIA', 'JAPAN', 'RUSSIA', 'USA']

In [67]:
# using map on function or using it with lambda function
f = map(lambda x: x.upper(), countries)
list(f)
# can use list infront of the map function to cast out the output

['INDIA', 'JAPAN', 'RUSSIA', 'USA']

In [69]:
# using map fuction to square root the list elements
l=[2,4,5]

list(map(lambda x: x**2,l))

[4, 16, 25]

In [71]:
# Othe way is to create variable for lambda function and use it map
square_root = lambda x: x**2
list(map(square_root,l))

[4, 16, 25]

In [92]:
# def sqrit(n):
#     l=[]
#     for i in n:
#         l.append(i**2)
#     return l

# sqrit(l)
        
def sqrit(n):
    return n**2


In [82]:
# Now map can be used on user defined function
list(map(sqrit,l))

[4, 16, 25]

#### Filter operation is similar to map function, only distinguishing feature being that it requires the function to look for a condition and then returns only those elements from the collection that satisfy the condition.

##### filter(function,iterable object)

    - The function object passed to the filter function should always return a boolean value.

    - The iterable object can be a string, list, tuple, set or dictionary.

In [91]:
# Filter operation
my_list=[3,4,5,6,7,8,9]

divby3= lambda x: x if x%3==0 else False

list(map(divby3, my_list))

[3, False, False, 6, False, False, 9]

In [94]:
# filter function returns the element once casted with list
div = filter(divby3, my_list)
list(div)

[3, 6, 9]

In [95]:
students_data = {1:['Sam', 15] , 2:['Rob',18], 3:['Kyle', 16], 4:['Cornor',19], 5:['Trump',20]}
students_data

{1: ['Sam', 15],
 2: ['Rob', 18],
 3: ['Kyle', 16],
 4: ['Cornor', 19],
 5: ['Trump', 20]}

In [106]:
f = lambda x: x[1] > 18
f(['Sam', 15])

False

In [110]:
# to find the data of students of 18 yrs of age
list(filter(f, students_data.values()))

[['Cornor', 19], ['Trump', 20]]

In [112]:
#to count the numbers of the students
len(list(filter(f, students_data.values())))

2

#### Reduce' is an operation that breaks down the entire process into pair-wise operations and uses the result from each operation, with the successive element. The syntax of reduce function is given below. 

 

reduce(function,iterable object)

    - The function object passed to the reduce function decides what expression is passed to the iterable object.
    - The iterable object can be a string, list, tuple, set or dictionary.
    - Also, reduce function produces a single output.

In [162]:
from functools import reduce
l=range(1,10)
list(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [163]:
# to multiply all digits between range(1,10)
f = lambda x,y: x*y
reduce(f,l)

362880

In [183]:
# Q. Count the number that start With 'S' using map
l=['Santa Cruz','Santa fe','Mumbai','Delhi']

# f=lambda x: x[0]=='S'
# d=list(map(f,l))
sum(map(lambda x: x[0]=='S',l))


2

In [198]:
l= ['Ankur', 'Avik', 'Kiran', 'Nitin']
b= ['Narang', 'Sarkar', 'R', 'Sareen']

In [201]:
f= lambda x,y: x+' '+y
list(map(f,l,b))

['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']

### Extract a list of numbers that are multiples of 5 from a list of integers named input_list.

In [204]:
l= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

In [206]:
f=lambda x: x%5==0
list(filter(f,l))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

### Extract a list of names that start with an ‘s’ and end with a ‘p’ (both 's' and 'p' are lowercase) in input_list.

In [215]:
l=  ['hdjk', 'salsap', 'sherpa']
f=lambda x: x if x[0]=='s' and x[-1]=='p' else False
list(filter(f,l))

['salsap']

### Using the Reduce function, concatenate a list of words in input_list, and print the output as a string.

If input_list = ['I','Love','Python'], the output should be the string 'I Love Python'.

In [222]:
l = ['All','you','have','to','fear','is','fear','itself']

f=lambda x,y: x+' '+y
str(reduce(f,l))

'All you have to fear is fear itself'

In [224]:
# find the largest number using reduce function
input_list = [31, 63, 76, 89]
f= lambda x,y: x if x > y else y
reduce(f, input_list)

89